### ISSUE TITLE
Uncaught Error: Class 'Dotenv\Environment\DotenvFactory' not found

### ISSUE THREAD

**Issue by Jakobud** [knowler/wp-capsule#3]
I think this would be helpful for plugin support. I'm getting this error though. I know with Laravel you typically use ENV files, but for Wordpress you really don't use those since credentials are defined in the wp-config.php. Is that required somehow? How do you do this?

**Comment by Jakobud** [comment]
I fixed the above issue by installing vlucas/phpdotenv, but now I get:

Fatal error: Uncaught InvalidArgumentException: Database hosts array is empty.

There are definitely some missing steps for installing this package. Not sure what to do. Do I have to define my database env in a .env file? Seems like these are unnecessary steps since this is already defined in wp-config.php.

**Comment by knowler** [comment]
> Do I have to define my database env in a .env file?

Yes, you would need to.

> Seems like these are unnecessary steps since this is already defined in wp-config.php.

I guess I neglected to add to the README that this package was created with the assumption that you would be using a WordPress boilerplate like [Bedrock](https://github.com/roots/bedrock). I will make a note about that. I would not create an `.env` file if you are using the standard WordPress project structure since that would expose the file and your secrets to the public. Bedrock places this file outside of [its public directory](https://github.com/roots/bedrock/tree/master/web). I highly recommend Bedrock for WordPress projects (I am biased), otherwise, I’m afraid that I don’t plan to add support for just using `wp-config.php`. I think there might be a few similar packages out there which do essentially do the same thing. Check out [deliciousbrains/wp-migrations](https://github.com/deliciousbrains/wp-migrations) for something that's a bit more polished.
